apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: homework
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: homework
  name: admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-admin
  namespace: homework
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cd
  namespace: homework
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: sa-cd-token
  namespace: homework
  annotations:
    kubernetes.io/service-account.name: cd
type: kubernetes.io/service-account-token