apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: homework
spec:
  containers:
  - name: my-nginx
    image: nginx:latest
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: workdir
      mountPath: "/homework"
    lifecycle:
      preStop:
        exec:
          command: ["sh", "-c","sleep 1 && rm /homework/index.html"]
  initContainers:
  - name: my-init
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/init/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: "/init"
  volumes:
  - name: workdir
    emptyDir: {}